CREATE CACHED TABLE PUBLIC.CONTENTANALYSES(
    ID VARCHAR NOT NULL,
    DATE VARCHAR,
     TYPEOFINPUTDOCUMENT VARCHAR,
    IP VARCHAR
);
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_9 ON PUBLIC.CONTENTANALYSES(ID);
ALTER TABLE PUBLIC.CONTENTANALYSES ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_9;
CREATE CACHED TABLE PUBLIC.ASCONTENTANALYSIS(
    ANNOTATIONS LONGVARBINARY,
    OVERALLQUALITY VARCHAR,
    OVERALLQUALITYMEASURE VARCHAR,
    TYPE VARCHAR,
    ORIGINAL_ID VARCHAR,
    TITLE VARCHAR,
    CONTENT LONGVARBINARY,
    STRINGCONTENT VARCHAR,
    CONTENTANALYSES_ID VARCHAR
);
CREATE INDEX PUBLIC.FK_ASCONTENTANALYSIS_CONTENTANALYSES_ID_INDEX_2 ON PUBLIC.ASCONTENTANALYSIS(CONTENTANALYSES_ID);
ALTER TABLE PUBLIC.ASCONTENTANALYSIS ADD CONSTRAINT PUBLIC.FK_ASCONTENTANALYSIS_CONTENTANALYSES_ID FOREIGN KEY(CONTENTANALYSES_ID) INDEX PUBLIC.FK_ASCONTENTANALYSIS_CONTENTANALYSES_ID_INDEX_2 REFERENCES PUBLIC.CONTENTANALYSES(ID) NOCHECK;